variables:
  IMAGE: "ghcr.io/astral-sh/uv:python3.12-bookworm"
  MYPY_CACHE_DIR: $CI_PROJECT_DIR/.mypy_cache
  UV_CACHE_DIR: $CI_PROJECT_DIR/.uv_cache


stages:
  - test
  - build


test:
  stage: test
  tags:
    - daedalus
  image: $IMAGE
  script:
    - uv sync
    - uv run python -m pytest --cov --cov-report=term --cov-report=xml --junit-xml=report.xml
    - uv run python -m mypy --no-error-summary docs src tests
    - uv run python -m reuse lint
    - uv run python -m ruff check docs src tests
    - uv run python -m ruff format --diff docs src tests
    - uv run sphinx-build docs public
  coverage: '/\d+\%\s*$/'
  artifacts:
    paths:
      - public
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: report.xml
  cache:
    key: checks
    paths:
      - .mypy_cache
      - .uv_cache


build:
  stage: build
  tags:
    - daedalus
  image: $IMAGE
  script:
    - uv sync
    - uv build
  artifacts:
    paths:
      - dist
  cache:
    key: checks
    paths:
      - .mypy_cache
      - .uv_cache
