version = 1
SPDX-PackageName = "sensorium"
SPDX-PackageSupplier = "Projectpraktikum Python <python.ldv@xcit.tum.de>"
SPDX-PackageDownloadLocation = "https://gitlab.lrz.de/ldv/teaching/python/2024"

[[annotations]]
path = ["**/kitti*/**/*.png", "**/kitti*/**/*.txt"]
path = ["**/kitti*/**/*.png", "**/kitti*/**/*.txt", "test_calib.txt", "test_poses.txt"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2004 KITTI"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [".gitignore", ".gitlab/**", "uv.lock", "**.toml", "**.yml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Projektpraktikum Python"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["**.rst", "**/**.rst"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Projektpraktikum Python"
SPDX-License-Identifier = "CC-BY-SA-4.0"
