# Copyright 2024  Projektpraktikum Python.
# SPDX-License-Identifier: Apache-2.0
backend_engine:
  data_dir: C:\Users\Oatty\Desktop\workspaces\semantic_kitti\dataset # like /home/jovyan/kitti_dummy/dataset
  # declare more parameters here to be used in the backend
